name: CI Pipeline

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step to write the Google credentials JSON to a file
      - name: Set up Google credentials
        run: |
          echo "${{ secrets.CREDENTIALS }}" > credentials.json

      # Continue with your application run, testing, or deployment
      - name: Run application
        run: python your_script.py
